world = [{u'id': u'1', u'objective_type': u'keep', u'points': u'25', u'type': u'Center'},
 {u'id': u'2', u'objective_type': u'keep', u'points': u'25', u'type': u'Center'},
 {u'id': u'3', u'objective_type': u'keep', u'points': u'25', u'type': u'Center'},
 {u'id': u'4', u'objective_type': u'camp', u'points': u'5', u'type': u'Center'},
 {u'id': u'5', u'objective_type': u'camp', u'points': u'5', u'type': u'Center'},
 {u'id': u'6', u'objective_type': u'camp', u'points': u'5', u'type': u'Center'},
 {u'id': u'7', u'objective_type': u'camp', u'points': u'5', u'type': u'Center'},
 {u'id': u'8', u'objective_type': u'camp', u'points': u'5', u'type': u'Center'},
 {u'id': u'9', u'objective_type': u'castle', u'points': u'35', u'type': u'Center'},
 {u'id': u'10', u'objective_type': u'camp', u'points': u'5', u'type': u'Center'},
 {u'id': u'11', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'12', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'13', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'14', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'15', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'16', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'17', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'18', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'19', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'20', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'21', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'22', u'objective_type': u'tower', u'points': u'10', u'type': u'Center'},
 {u'id': u'23', u'objective_type': u'keep', u'points': u'25', u'type': u'BlueHome'},
 {u'id': u'24', u'objective_type': u'camp', u'points': u'5', u'type': u'BlueHome'},
 {u'id': u'25', u'objective_type': u'tower', u'points': u'10', u'type': u'BlueHome'},
 {u'id': u'26', u'objective_type': u'tower', u'points': u'10', u'type': u'BlueHome'},
 {u'id': u'27', u'objective_type': u'keep', u'points': u'25', u'type': u'BlueHome'},
 {u'id': u'28', u'objective_type': u'tower', u'points': u'10', u'type': u'BlueHome'},
 {u'id': u'29', u'objective_type': u'camp', u'points': u'5', u'type': u'BlueHome'},
 {u'id': u'30', u'objective_type': u'tower', u'points': u'10', u'type': u'BlueHome'},
 {u'id': u'31', u'objective_type': u'keep', u'points': u'25', u'type': u'BlueHome'},
 {u'id': u'32', u'objective_type': u'keep', u'points': u'25', u'type': u'RedHome'},
 {u'id': u'33', u'objective_type': u'keep', u'points': u'25', u'type': u'RedHome'},
 {u'id': u'34', u'objective_type': u'camp', u'points': u'5', u'type': u'RedHome'},
 {u'id': u'35', u'objective_type': u'tower', u'points': u'10', u'type': u'RedHome'},
 {u'id': u'36', u'objective_type': u'tower', u'points': u'10', u'type': u'RedHome'},
 {u'id': u'37', u'objective_type': u'keep', u'points': u'25', u'type': u'RedHome'},
 {u'id': u'38', u'objective_type': u'tower', u'points': u'10', u'type': u'RedHome'},
 {u'id': u'39', u'objective_type': u'camp', u'points': u'5', u'type': u'RedHome'},
 {u'id': u'40', u'objective_type': u'tower', u'points': u'10', u'type': u'RedHome'},
 {u'id': u'41', u'objective_type': u'keep', u'points': u'25', u'type': u'GreenHome'},
 {u'id': u'42', u'objective_type': u'tower', u'points': u'10', u'type': u'GreenHome'},
 {u'id': u'43', u'objective_type': u'camp', u'points': u'5', u'type': u'GreenHome'},
 {u'id': u'44', u'objective_type': u'keep', u'points': u'25', u'type': u'GreenHome'},
 {u'id': u'45', u'objective_type': u'tower', u'points': u'10', u'type': u'GreenHome'},
 {u'id': u'46', u'objective_type': u'keep', u'points': u'25', u'type': u'GreenHome'},
 {u'id': u'47', u'objective_type': u'tower', u'points': u'10', u'type': u'GreenHome'},
 {u'id': u'48', u'objective_type': u'camp', u'points': u'5', u'type': u'GreenHome'},
 {u'id': u'49', u'objective_type': u'camp', u'points': u'5', u'type': u'GreenHome'},
 {u'id': u'50', u'objective_type': u'camp', u'points': u'5', u'type': u'RedHome'},
 {u'id': u'51', u'objective_type': u'camp', u'points': u'5', u'type': u'RedHome'},
 {u'id': u'52', u'objective_type': u'camp', u'points': u'5', u'type': u'RedHome'},
 {u'id': u'53', u'objective_type': u'camp', u'points': u'5', u'type': u'RedHome'},
 {u'id': u'54', u'objective_type': u'camp', u'points': u'5', u'type': u'GreenHome'},
 {u'id': u'55', u'objective_type': u'camp', u'points': u'5', u'type': u'GreenHome'},
 {u'id': u'56', u'objective_type': u'camp', u'points': u'5', u'type': u'GreenHome'},
 {u'id': u'57', u'objective_type': u'tower', u'points': u'10', u'type': u'GreenHome'},
 {u'id': u'58', u'objective_type': u'camp', u'points': u'5', u'type': u'BlueHome'},
 {u'id': u'59', u'objective_type': u'camp', u'points': u'5', u'type': u'BlueHome'},
 {u'id': u'60', u'objective_type': u'camp', u'points': u'5', u'type': u'BlueHome'},
 {u'id': u'61', u'objective_type': u'camp', u'points': u'5', u'type': u'BlueHome'}]

lang = {u'1': (u'Overlook', u'Aussichtspunkt', u'Belv\xe9d\xe8re', u''),
 u'10': (u'Rogues Quarry', u'Schurkenbruch', u'Carri\xe8re des voleurs', u''),
 u'11': (u'Aldons Ledge', u'Aldons Vorsprung', u'Corniche dAldon', u''),
 u'12': (u'Wildcreek Run', u'Wildbachstrecke', u'Piste du Ruisseau sauvage', u''),
 u'13': (u'Jerrifers Slough', u'Jerrifers Sumpfloch', u'Bourbier de Jerrifer', u''),
 u'14': (u'Klovan Gully', u'Klovan-Senke', u'Petit ravin de Klovan', u''),
 u'15': (u'Langor Gulch', u'Langor-Schlucht', u'Ravin de Langor', u''),
 u'16': (u'Quentin Lake', u'Quentinsee', u'Lac Quentin', u''),
 u'17': (u'Mendons Gap', u'Mendons Spalt', u'Faille de Mendon', u''),
 u'18': (u'Anzalias Pass', u'Anzalias-Pass', u'Col dAnzalias', u''),
 u'19': (u'Ogrewatch Cut', u'Ogerwacht-Kanal', u'Perc\xe9e de Gardogre', u''),
 u'2': (u'Valley', u'Tal', u'Vall\xe9e', u''),
 u'20': (u'Veloka Slope', u'Veloka-Hang', u'Flanc de Veloka', u''),
 u'21': (u'Durios Gulch', u'Durios-Schlucht', u'Ravin de Durios', u''),
 u'22': (u'Bravost Escarpment', u'Bravost-Abhang', u'Falaise de Bravost', u''),
 u'23': (u'Garrison', u'Festung', u'Garnison', u''),
 u'24': (u'Champions demense', u'Landgut des Champions', u'Fief du champion', u''),
 u'25': (u'Redbriar', u'Rotdornstrauch', u'Bruyerouge', u''),
 u'26': (u'Greenlake', u'Gr\xfcnsee', u'Lac Vert', u''),
 u'27': (u'Ascension Bay', u'Bucht des Aufstiegs', u'Baie de lAscension', u''),
 u'28': (u'Dawns Eyrie', u'Horst der Morgend\xe4mmerung', u'Promontoire de laube', u''),
 u'29': (u'The Spiritholme', u'Der Geisterholm', u'Lantre des esprits', u''),
 u'3': (u'Lowlands', u'Tiefland', u'Basses terres', u''),
 u'30': (u'Woodhaven', u'Wald-Freistatt', u'Gentesylve', u''),
 u'31': (u'Askalion Hills', u'Askalion-H\xfcgel', u'Collines dAskalion', u''),
 u'32': (u'Etheron Hills', u'Etheron-H\xfcgel', u'Collines dEtheron', u''),
 u'33': (u'Dreaming Bay', u'Traumbucht', u'Baie des r\xeaves', u''),
 u'34': (u'Victorss Lodge', u'Sieger-H\xfctte', u'Pavillon du vainqueur', u''),
 u'35': (u'Greenbriar', u'Gr\xfcnstrauch', u'Vertebranche', u''),
 u'36': (u'Bluelake', u'Blausee', u'Lac bleu', u''),
 u'37': (u'Garrison', u'Festung', u'Garnison', u''),
 u'38': (u'Longview', u'Weitsicht', u'Longuevue', u''),
 u'39': (u'The Godsword', u'Das Gottschwert', u'LEp\xe9e divine', u''),
 u'4': (u'Golanta Clearing', u'Golanta-Lichtung', u'Clairi\xe8re de Golanta', u''),
 u'40': (u'Cliffside', u'Felswand', u'Flanc de falaise', u''),
 u'41': (u'Shadaran Hills', u'Shadaran-H\xfcgel', u'Collines de Shadaran', u''),
 u'42': (u'Redlake', u'Rotsee', u'Rougelac', u''),
 u'43': (u'Heros Lodge', u'H\xfctte des Helden', u'Pavillon du H\xe9ros', u''),
 u'44': (u'Dreadfall Bay', u'Schreckensfall-Bucht', u'Baie du Noir d\xe9clin', u''),
 u'45': (u'Bluebriar', u'Blaudornstrauch', u'Bruyazur', u''),
 u'46': (u'Garrison', u'Festung', u'Garnison', u''),
 u'47': (u'Sunnyhill', u'Sonnenlichth\xfcgel', u'Colline ensoleill\xe9e', u''),
 u'48': (u'Faithleap', u'Glaubenssprung', u'Ferveur', u''),
 u'49': (u'Bluevale Refuge', u'Blautal-Zuflucht', u'Refuge de bleubal', u''),
 u'5': (u'Pangloss Rise', u'Pangloss-Anh\xf6he', u'Mont\xe9e de Pangloss', u''),
 u'50': (u'Bluewater Lowlands', u'Blauwasser-Tiefland', u'Basses terres dEau-Azur', u''),
 u'51': (u'Astralholme', u'Astralholm', u'Astralholme', u''),
 u'52': (u'Arahs Hope', u'Arahs Hoffnung', u'Espoir dArah', u''),
 u'53': (u'Greenvale Refuge', u'Gr\xfcntal-Zuflucht', u'Refuge de Valvert', u''),
 u'54': (u'Foghaven', u'Nebel-Freistatt', u'Havre gris', u''),
 u'55': (u'Redwater Lowlands', u'Rotwasser-Tiefland', u'Basses terres de Rubicon', u''),
 u'56': (u'The Titanpaw', u'Die Titanenpranke', u'Bras du titan', u''),
 u'57': (u'Cragtop', u'Felsenspitze', u'Sommet de lescarpement', u''),
 u'58': (u'Godslore', u'G\xf6tterkunde', u'Divination', u''),
 u'59': (u'Redvale Refuge', u'Rottal-Zuflucht', u'Refuge de Valrouge', u''),
 u'6': (u'Speldan Clearcut', u'Speldan Kahlschlag', u'For\xeat ras\xe9e de Speldan', u''),
 u'60': (u'Stargrove', u'Sternenhain', u'Bosquet stellaire', u''),
 u'61': (u'Greenwater Lowlands', u'Gr\xfcnwasser-Tiefland', u'Basses terres dEau-Verdoyante', u''),
 u'7': (u'Danelon Passage', u'Danelon-Passage', u'Passage Danelon', u''),
 u'8': (u'Umberglade Woods', u'Umberlichtung-Forst', u'Bois dOmbreclair', u''),
 u'9': (u'Stonemist Castle', u'Schloss Steinnebel', u'Ch\xe2teau Brumepierre', u'')}